services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - 25672:25672
      - 15672:15672
      - 5672:5672
    volumes:
      - .docker_conf/rabbitmq:/var/lib/rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
    restart: always
volumes:
  log-folder:
    name: ${log_rabbitmq_management}
    driver: local
